-- MindSeed quotes (v2, curated)
-- Vietnamese: 31 kept + 12 fixed from Vietnamese_Quote_Dataset_100K
--            + tục ngữ / ca dao / 6 câu văn học
-- English: curated famous quotes
-- Categories: Học tập / Tập trung / Kỷ luật và kiên trì / Phát triển bản thân / Ca dao và tục ngữ / Cuộc sống và vui vẻ

create table if not exists public.quotes (
  id          uuid primary key default gen_random_uuid(),
  content     text not null check (char_length(content) between 1 and 500),
  author      text,
  category    text,
  lang        text not null default 'vi',
  created_at  timestamptz not null default now()
);

create unique index if not exists quotes_content_lang_uniq on public.quotes (content, lang);

alter table public.quotes enable row level security;

create policy "quotes_read_public"
  on public.quotes for select
  to anon, authenticated
  using (true);

insert into public.quotes (content, author, category, lang) values
  ('Những giấc mơ của bạn hôm nay tạo nên tương lai của bạn.', null, 'Phát triển bản thân', 'vi'),
  ('Bất cứ khi nào có cơ hội, chúng ta phải nỗ lực hết mình.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Ý chí vươn lên khi bạn vấp ngã là dũng khí để thành công.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Những gì bạn làm hôm nay là nền móng cho tương lai của bạn.', null, 'Phát triển bản thân', 'vi'),
  ('Mỗi năm, chúng ta có 365 cơ hội để bắt đầu một cuộc đời mới.', null, 'Phát triển bản thân', 'vi'),
  ('Đừng cố gắng sửa chữa quá khứ, hãy cố gắng xây dựng tương lai.', null, 'Phát triển bản thân', 'vi'),
  ('Nếu chúng ta không thay đổi, chúng ta sẽ không học hỏi được gì.', null, 'Học tập', 'vi'),
  ('Để giữ mãi tuổi trẻ, hãy chấp nhận thay đổi và tiếp tục học hỏi.', null, 'Học tập', 'vi'),
  ('Hãy làm việc gì đó vì nó tốt đẹp, đừng chỉ vì nó có cơ hội thành công.', null, 'Phát triển bản thân', 'vi'),
  ('Hãy học hỏi tất cả những gì bạn có thể.', null, 'Học tập', 'vi'),
  ('Bạn chỉ thất bại khi bạn ngừng cố gắng.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Không ai có quyền dập tắt ước mơ của bạn!', null, 'Phát triển bản thân', 'vi'),
  ('Điều gì bạn tập trung vào sẽ được mở rộng.', null, 'Tập trung', 'vi'),
  ('Nếu bạn không bắt đầu, bạn đã kết thúc rồi.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Thành công là kết quả của sự nỗ lực của bạn.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Hãy bắt đầu ngay cả khi bạn không biết cách.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Trong cuộc sống của bạn, đừng quên sống.', null, 'Cuộc sống và vui vẻ', 'vi'),
  ('Hành động của bạn hôm nay xác định ngày mai.', null, 'Phát triển bản thân', 'vi'),
  ('Học để tiếp thu kiến thức, đừng học để qua môn.', null, 'Học tập', 'vi'),
  ('Đừng từ bỏ bản thân, ước mơ và gia đình của bạn.', null, 'Phát triển bản thân', 'vi'),
  ('Hãy tìm tòi học hỏi không ngừng khi bạn còn sống.', null, 'Học tập', 'vi'),
  ('Trở ngại là thước đo cho cường độ đam mê của bạn.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Đừng sợ thất bại mà hãy sợ thành công tầm thường.', null, 'Phát triển bản thân', 'vi'),
  ('Hãy thất bại sớm để bạn có thể thành công sớm hơn.', null, 'Phát triển bản thân', 'vi'),
  ('Đừng để việc học hành cản trở việc giáo dục của bạn.', null, 'Học tập', 'vi'),
  ('Hãy đọc sách mỗi ngày và học hỏi từ những gì bạn đọc.', null, 'Học tập', 'vi'),
  ('Hãy học từ những sai lầm của bạn và đừng lặp lại chúng.', null, 'Học tập', 'vi'),
  ('Vào cuối mỗi ngày, bạn tiến gần hơn đến mục tiêu của mình.', null, 'Phát triển bản thân', 'vi'),
  ('Động lực giúp bạn bắt đầu, và thói quen giúp bạn đến đích.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Sai lầm và lỗi lầm là những bài học giúp chúng ta tiến bộ.', null, 'Học tập', 'vi'),
  ('Nếu chúng ta bỏ cuộc quá sớm, chúng ta sẽ bỏ lỡ thành công.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Kiên định với ước mơ của mình.', null, 'Phát triển bản thân', 'vi'),
  ('Hãy luôn giữ cho mình một niềm đam mê.', null, 'Phát triển bản thân', 'vi'),
  ('Đã đến lúc bắt đầu sống cuộc đời mà bạn hằng mơ ước.', null, 'Phát triển bản thân', 'vi'),
  ('Khi tin vào chính mình, bạn có thể tiến gần hơn tới mục tiêu.', null, 'Phát triển bản thân', 'vi'),
  ('Hy vọng ngày mai, ta sẽ trưởng thành hơn từ những gì đã học hôm nay.', null, 'Học tập', 'vi'),
  ('Hãy kiên trì với điều bạn thực sự đam mê.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Hãy quyết tâm biến ước mơ thành hành động.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Kiên trì đủ lâu, bạn sẽ tiến gần hơn đến thành công.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Hãy tự tạo nên cuộc sống mà bạn mong muốn.', null, 'Phát triển bản thân', 'vi'),
  ('Hãy can đảm theo đuổi điều bạn thực sự mong muốn.', null, 'Phát triển bản thân', 'vi'),
  ('Bạn dần trở thành con người mà mình dành thời gian và sự tập trung để hướng tới.', null, 'Tập trung', 'vi'),
  ('Bạn có thể đi rất xa khi đặt tâm trí và nỗ lực vào một điều.', null, 'Kỷ luật và kiên trì', 'vi'),
  ('Không có việc gì khó, chỉ sợ lòng không bền. Đào núi và lấp biển, quyết chí ắt làm nên.', 'Hồ Chí Minh', 'Văn học', 'vi'),
  ('Đường đi khó không phải vì ngăn sông cách núi, mà khó vì lòng người ngại núi e sông.', 'Nguyễn Bá Học', 'Văn học', 'vi'),
  ('Thà một phút huy hoàng rồi chợt tối, còn hơn buồn le lói suốt trăm năm.', 'Xuân Diệu', 'Văn học', 'vi'),
  ('Dù ai nói ngả nói nghiêng, lòng ta vẫn vững như kiềng ba chân.', 'Ca dao', 'Văn học', 'vi'),
  ('Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao.', 'Ca dao', 'Văn học', 'vi'),
  ('Ai ơi bưng bát cơm đầy, dẻo thơm một hạt đắng cay muôn phần.', 'Ca dao', 'Văn học', 'vi'),
  ('Học ăn, học nói, học gói, học mở.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Đi một ngày đàng, học một sàng khôn.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Có học mới hay, có cày mới biết.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Người không học như ngọc không mài.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Học thầy không tày học bạn.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Dao có mài mới sắc, người có học mới nên.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Có công mài sắt, có ngày nên kim.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Muốn biết phải hỏi, muốn giỏi phải học.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Học đi đôi với hành.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Trăm hay không bằng tay quen.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Học một, biết mười.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Luyện mãi thành tài, miệt mài tất giỏi.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Cần cù bù thông minh.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Không thầy đố mày làm nên.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Học hay cày biết.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Dốt đến đâu học lâu cũng biết.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Bảy mươi còn học bảy mươi mốt.', 'Tục ngữ', 'Học tập', 'vi'),
  ('Có chí thì nên.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Nước chảy đá mòn.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Kiến tha lâu cũng đầy tổ.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Chớ thấy sóng cả mà ngã tay chèo.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Lửa thử vàng, gian nan thử sức.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Thua keo này, bày keo khác.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Vạn sự khởi đầu nan.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Thất bại là mẹ thành công.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Tay làm hàm nhai, tay quai miệng trễ.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Tích tiểu thành đại.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Năng nhặt chặt bị.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Có chí làm quan, có gan làm giàu.', 'Tục ngữ', 'Kỷ luật và kiên trì', 'vi'),
  ('Một nghề cho chín còn hơn chín nghề.', 'Tục ngữ', 'Tập trung', 'vi'),
  ('Việc hôm nay chớ để ngày mai.', 'Tục ngữ', 'Tập trung', 'vi'),
  ('Chậm mà chắc.', 'Tục ngữ', 'Tập trung', 'vi'),
  ('Nhất nghệ tinh, nhất thân vinh.', 'Tục ngữ', 'Tập trung', 'vi'),
  ('Gần mực thì đen, gần đèn thì sáng.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Ăn quả nhớ kẻ trồng cây.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Uống nước nhớ nguồn.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Lá lành đùm lá rách.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Sau cơn mưa, trời lại sáng.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Chim khôn kêu tiếng rảnh rang, người khôn nói tiếng dịu dàng dễ nghe.', 'Ca dao', 'Cuộc sống và vui vẻ', 'vi'),
  ('Ở hiền gặp lành.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Góp gió thành bão.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Nhiễu điều phủ lấy giá gương, người trong một nước phải thương nhau cùng.', 'Ca dao', 'Cuộc sống và vui vẻ', 'vi'),
  ('Của bền tại người.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Cây ngay không sợ chết đứng.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Giấy rách phải giữ lấy lề.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('Chia ngọt sẻ bùi.', 'Tục ngữ', 'Cuộc sống và vui vẻ', 'vi'),
  ('The beautiful thing about learning is that no one can take it away from you.', 'B.B. King', 'Học tập', 'en'),
  ('Live as if you were to die tomorrow. Learn as if you were to live forever.', 'Mahatma Gandhi', 'Học tập', 'en'),
  ('Education is the most powerful weapon which you can use to change the world.', 'Nelson Mandela', 'Học tập', 'en'),
  ('The more that you read, the more things you will know.', 'Dr. Seuss', 'Học tập', 'en'),
  ('Learning never exhausts the mind.', 'Leonardo da Vinci', 'Học tập', 'en'),
  ('Tell me and I forget, teach me and I remember, involve me and I learn.', 'Benjamin Franklin', 'Học tập', 'en'),
  ('An investment in knowledge pays the best interest.', 'Benjamin Franklin', 'Học tập', 'en'),
  ('The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.', 'Brian Herbert', 'Học tập', 'en'),
  ('Change is the end result of all true learning.', 'Leo Buscaglia', 'Học tập', 'en'),
  ('Anyone who stops learning is old, whether at twenty or eighty.', 'Henry Ford', 'Học tập', 'en'),
  ('The mind is not a vessel to be filled, but a fire to be kindled.', 'Plutarch', 'Học tập', 'en'),
  ('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'Học tập', 'en'),
  ('The roots of education are bitter, but the fruit is sweet.', 'Aristotle', 'Học tập', 'en'),
  ('Curiosity is the wick in the candle of learning.', 'William Arthur Ward', 'Học tập', 'en'),
  ('Formal education will make you a living; self-education will make you a fortune.', 'Jim Rohn', 'Học tập', 'en'),
  ('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'Tập trung', 'en'),
  ('Where focus goes, energy flows.', 'Tony Robbins', 'Tập trung', 'en'),
  ('Concentrate all your thoughts upon the work in hand.', 'Alexander Graham Bell', 'Tập trung', 'en'),
  ('Lack of direction, not lack of time, is the problem.', 'Zig Ziglar', 'Tập trung', 'en'),
  ('It is not that I am so smart, it is just that I stay with problems longer.', 'Albert Einstein', 'Tập trung', 'en'),
  ('The ability to focus is the keystone of excellence.', 'Debbie Ford', 'Tập trung', 'en'),
  ('You can do anything, but not everything.', 'David Allen', 'Tập trung', 'en'),
  ('The shortest answer is doing the thing.', 'Ernest Hemingway', 'Tập trung', 'en'),
  ('Simplicity is the ultimate sophistication.', 'Leonardo da Vinci', 'Tập trung', 'en'),
  ('Efficiency is doing things right; effectiveness is doing the right things.', 'Peter Drucker', 'Tập trung', 'en'),
  ('You can never be overdressed or overeducated.', 'Oscar Wilde', 'Tập trung', 'en'),
  ('Discipline is the bridge between goals and accomplishment.', 'Jim Rohn', 'Kỷ luật và kiên trì', 'en'),
  ('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'Kỷ luật và kiên trì', 'en'),
  ('Fall seven times, stand up eight.', 'Japanese Proverb', 'Kỷ luật và kiên trì', 'en'),
  ('Perseverance is not a long race; it is many short races one after another.', 'Walter Elliott', 'Kỷ luật và kiên trì', 'en'),
  ('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'Kỷ luật và kiên trì', 'en'),
  ('The secret of getting ahead is getting started.', 'Mark Twain', 'Kỷ luật và kiên trì', 'en'),
  ('Success is the sum of small efforts repeated day in and day out.', 'Robert Collier', 'Kỷ luật và kiên trì', 'en'),
  ('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'Kỷ luật và kiên trì', 'en'),
  ('Genius is one percent inspiration, ninety-nine percent perspiration.', 'Thomas Edison', 'Kỷ luật và kiên trì', 'en'),
  ('Small daily improvements are the key to staggering long-term results.', 'Robin Sharma', 'Kỷ luật và kiên trì', 'en'),
  ('Dream big. Start small. Act now.', 'Robin Sharma', 'Kỷ luật và kiên trì', 'en'),
  ('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Kỷ luật và kiên trì', 'en'),
  ('It always seems impossible until it is done.', 'Nelson Mandela', 'Kỷ luật và kiên trì', 'en'),
  ('The best way out is always through.', 'Robert Frost', 'Kỷ luật và kiên trì', 'en'),
  ('A river cuts through rock, not because of its power, but because of its persistence.', 'James N. Watkins', 'Kỷ luật và kiên trì', 'en'),
  ('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'Phát triển bản thân', 'en'),
  ('The only way to do great work is to love what you do.', 'Steve Jobs', 'Phát triển bản thân', 'en'),
  ('Believe you can and you are halfway there.', 'Theodore Roosevelt', 'Phát triển bản thân', 'en'),
  ('Act as if what you do makes a difference. It does.', 'William James', 'Phát triển bản thân', 'en'),
  ('Whether you think you can or you think you can''t, you''re right.', 'Henry Ford', 'Phát triển bản thân', 'en'),
  ('The best way to predict the future is to create it.', 'Peter Drucker', 'Phát triển bản thân', 'en'),
  ('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'Phát triển bản thân', 'en'),
  ('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'Phát triển bản thân', 'en'),
  ('Strive not to be a success, but rather to be of value.', 'Albert Einstein', 'Phát triển bản thân', 'en'),
  ('Your time is limited, so don''t waste it living someone else''s life.', 'Steve Jobs', 'Phát triển bản thân', 'en'),
  ('Do not wait; the time will never be ''just right''.', 'Napoleon Hill', 'Phát triển bản thân', 'en'),
  ('You are braver than you believe, stronger than you seem, and smarter than you think.', 'A.A. Milne', 'Phát triển bản thân', 'en'),
  ('A journey of a thousand miles begins with a single step.', 'Lao Tzu', 'Phát triển bản thân', 'en'),
  ('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'Phát triển bản thân', 'en'),
  ('If you cannot do great things, do small things in a great way.', 'Napoleon Hill', 'Phát triển bản thân', 'en'),
  ('Chase the vision, not the money; the money will end up following you.', 'Tony Hsieh', 'Phát triển bản thân', 'en'),
  ('Life is what happens when you are busy making other plans.', 'John Lennon', 'Cuộc sống và vui vẻ', 'en'),
  ('Don''t count the days, make the days count.', 'Muhammad Ali', 'Cuộc sống và vui vẻ', 'en'),
  ('Enjoy the little things, for one day you may look back and realize they were the big things.', 'Robert Brault', 'Cuộc sống và vui vẻ', 'en'),
  ('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'Cuộc sống và vui vẻ', 'en'),
  ('Smile, breathe, and go slowly.', 'Thich Nhat Hanh', 'Cuộc sống và vui vẻ', 'en'),
  ('Happiness is not something ready made. It comes from your own actions.', 'Dalai Lama', 'Cuộc sống và vui vẻ', 'en'),
  ('The best time to plant a tree was twenty years ago. The second best time is now.', 'Chinese Proverb', 'Cuộc sống và vui vẻ', 'en'),
  ('The purpose of our lives is to be happy.', 'Dalai Lama', 'Cuộc sống và vui vẻ', 'en'),
  ('A day without laughter is a day wasted.', 'Charlie Chaplin', 'Cuộc sống và vui vẻ', 'en'),
  ('Keep smiling, because life is a beautiful thing and there is so much to smile about.', 'Marilyn Monroe', 'Cuộc sống và vui vẻ', 'en')
on conflict (content, lang) do nothing;

create index if not exists quotes_lang_idx on public.quotes (lang);
